# Make sure minimal version is snakemake 8
from snakemake.utils import min_version
min_version("8")

# Load configuration
configfile: "config/config.yaml"

# Include modules
include: "rules/common.smk"
include: "rules/agat.smk"
include: "rules/1.assembly/all.smk"
include: "rules/2.scaffolding/all.smk"
include: "rules/3.analysis/all.smk"
include: "rules/4.annotation/all.smk"
include: "rules/5.quality_control/all.smk"

# Define global wildcard constraints
wildcard_constraints:
    minlen="\\d+"

# Define output of all modules
rule all:
    input:
        "results/assembly.done",
        "results/scaffolding.done",
        "results/analysis.done",
        "results/annotation.done",
        "results/quality_control.done",
