from snakemake.utils import min_version
min_version("8.4")

configfile: "config/config.yaml" 

include: "rules/assembly/all.smk"
include: "rules/scaffolding/all.smk"
include: "rules/cleaning/all.smk"
include: "rules/annotation/all.smk"
include: "rules/quality_control/all.smk"

rule all: 
    input: 
        "results/assembly/.done",
        "results/scaffolding/.done",
        "results/cleaning/.done",
        "results/annotation/.done",
        "results/quality_control/.done",
