# This file contains the full configuration for the pipeline in YAML format.
# Make sure to fill out at least everything that is not labelled as optional.
# All strings that start with "resources" should be relative or absolute paths
# on your machine that are readable by Snakemake.

# All samples should be defined in a TSV file. In this file, a unique
# accessionId, path to HiFi reads, (optional) path to ONT reads, (optional)
# paths to Illumina reads, species name, NCBI taxonomy ID, and reference genome
# ID should be defined.
samples: "config/samples.tsv"

# All filtering and scaffolding parameters
min_contig_len: 10000
ntjoin_k: 52
ntjoin_w: 16000

# All reference genomes and chromosomes. The reference genome ID in the samples
# sheet should match the key in this section.
reference_genomes:
    referenceA:
        genome: "resources/reference_genome_A.fa"
        annotation: "resources/reference_genome_A.gff"
        chromosomes:
            1: "Chr1"
            2: "Chr2"
            3: "Chr3"
            4: "Chr4"
            5: "Chr5"
    referenceB:
        genome: "resources/reference_genome_B.fa"
        annotation: "resources/reference_genome_B.gff"
        chromosomes:
            1: "Chr1"
            2: "Chr2"
            3: "Chr3"
            4: "Chr4"
            5: "Chr5"
            6: "Chr6"

# All protein and nucleotide queries that need to be run for the assembly
# analysis module (circos plot)
prot_queries: #should be single exon domains only!
    NBS_domain: "resources/blast_queries/query1.amac"
nucl_queries:
    chloroplast: "resources/blast_queries/chloroplast.fasta"
    mitochondrion: "resources/blast_queries/mitochondrion.fasta"
    telomere: "resources/blast_queries/telomere.fasta"

# Annotation settings
helixer_model: "resources/land_plant_v0.3_a_0080.h5"
helixer_max_gene_length: 64152

# Quality control settings
k_qc: 21  #optimal k-mer size for quality control
gxdb: "resources/gxdb"  #path to gxdb for fcs-gx
pantools_grouping: 3  #grouping relaxation setting for pantools
odb: "viridiplantae_odb10"  #ODB database for busco
kraken2_nt: "resources/kraken/nt"  #kraken2 database
OMAdb: "resources/OMAmerDB.h5"  #OMA database for orthologs

# A section to define groups of accessions for plotting together in report. This
# list is order sensitive and will only be used for QC.
set:
    all:
        - accessionA
        - accessionB
        - accessionC

# General settings
jvm: "-Xmx100g -Xms100g"  #java virtual machine settings
tmpdir: "/dev/shm/"  #temporary directory for fast IO
