# Here we define all input read sets. Using the same identifier for hifi and ont
# will result in using both for the same assembly
reads:
    hifi:
        accessionA: "/path_to_data/accessionA/HiFi/readsA.fasta"
        accessionB: "/path_to_data/accessionA/HiFi/readsB.fasta"
    ont:
        accessionA: "/path_to_data/accessionA/ONT/readsA.fasta"

# Here we define all parameters needed for filtering and scaffolding the genome
ref_genome: "/path_to_data/reference_genome.fa"
minlen: 10000
k: 21
w: 7

# Here we define all protein and nucleotide queries that need to be run for the
# assembly analysis module
prot_queries:
    NBS_domain: "/path_to_data/blast_queries/query1.amac"
nucl_queries:
    chloroplast: "/path_to_data/blast_queries/chloroplast.fasta"
    mitochondrion: "/path_to_data/blast_queries/mitochondrion.fasta"
    telomere: "/path_to_data/blast_queries/telomere.fasta"

