# This file contains the full configuration for the pipeline in YAML format.
# Make sure to fill out at least everything that is not labelled as optional.
# All strings that start with "resources" should be relative or absolute paths
# on your machine that are readable by Snakemake.

# All samples should be defined in a TSV file. In this file, a unique
# accessionId, path to HiFi reads, (optional) path to ONT reads, (optional)
# paths to Illumina reads, species name, NCBI taxonomy ID, and reference genome
# ID should be defined.
samples: "config/samples.tsv"

# Assembly settings
assembler: "hifiasm"  #supported assemblers: hifiasm, verkko

# All filtering and scaffolding parameters
min_contig_len: 10000
ntjoin_k: 52
ntjoin_w: 16000

# All reference genomes and chromosomes. The reference genome ID in the samples
# sheet should match the key in this section.
reference_genomes:
    GRCh38:
        genome: "resources/human/GCA_000001405.29_GRCh38.p14_genomic.fna"
        annotation: "resources/human/gencode.v46.chr_patch_hapl_scaff.annotation.fixed.gff3"
        chromosomes:
            1: "CM000663.2"
            2: "CM000664.2"
            3: "CM000665.2"
            4: "CM000666.2"
            5: "CM000667.2"
            6: "CM000668.2"
            7: "CM000669.2"
            8: "CM000670.2"
            9: "CM000671.2"
            10: "CM000672.2"
            11: "CM000673.2"
            12: "CM000674.2"
            13: "CM000675.2"
            14: "CM000676.2"
            15: "CM000677.2"
            16: "CM000678.2"
            17: "CM000679.2"
            18: "CM000680.2"
            19: "CM000681.2"
            20: "CM000682.2"
            21: "CM000683.2"
            22: "CM000684.2"
            X: "CM000685.2"
            Y: "CM000686.2"

# All protein and nucleotide queries that need to be run for the assembly
# analysis module. The key should be the name of the query and the value should
# be the path to the query. At least one protein or nucleotide query is
# required for the module to run (organellar sequences count as nucleotide
# queries).
# Contigs with a more than 50% of its length covered by an organellar sequence
# will be separated from the scaffolded assembly output (not for QC, though).
# For the protein queries, the query should be a single exon domain as it
# is searched in the genome and not in the proteome.
prot_queries:
    hox: "resources/human/HOX.amac"
nucl_queries:
    telomere: "resources/human/telomere.fasta"
organellar:
    mitochondrion: "resources/human/mitochondrion.fasta"
telomere_motif: "AACCCT"

# Annotation settings
helixer_model: "resources/vertebrate_v0.3_m_0080.h5"
helixer_max_gene_length: 64152

# Quality assessment settings
k_qa: 21  #optimal k-mer size for quality assessment
gxdb: "/local/fcs/gxdb"  #path to gxdb for fcs-gx
pantools_grouping: 3  #grouping relaxation setting for pantools
odb: "primates_odb10"  #ODB database for busco
kraken2_nt: "/path/to/kraken2/nt"  #kraken2 database
OMAdb: "/path/to/oma_databases/LUCA.h5"  #OMA database for orthologs

# A section to define groups of accessions for plotting together in report. This
# list is order sensitive and will only be used for QC.
set:
    human_all:
        - HG002
        - HG003
        - HG004

# General settings; only change if you know what you are doing
jvm: "-Xmx100g -Xms100g"  #java virtual machine settings
tmpdir: "/dev/shm/tmp_human"  #temporary directory for fast IO
nucmer_maxgap: 1000  #maximum gap size for nucmer
nucmer_minmatch: 1000  #minimum match size for nucmer
